# -*- coding: utf-8 -*-
"""Session 4_1024.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hOS01mQf1z5NIdgX-tSRd9c0fDKsHgPF
"""

n = int(input("Enter the number of terms: "))

a = 0
b = 1

print("Fibonacci Series:", end=" ")

for i in range(1, n + 1):
    print(a, end=" ")
    next_num = a + b
    a = b
    b = next_num

#include <stdio.h>

struct Student {
    char name[50];
    int rollNo;
    float marks;
};

int main() {
    struct Student s = {"Rahul", 4, 87.9};

    printf("Student Details:\n");
    printf("Name: %s\n", s.name);
    printf("Roll No: %d\n", s.rollNo);
    printf("Marks: %.1f\n", s.marks);

    return 0;
}